batch_size: 100
decision_strategy: prob
envelope_threshold: 1
flat_sample: true
flat_width: 1
from_scratch: true
gamma: 0.95
global_seed: 0
learning_strategy: bayes_optimistic
load: null
max_steps: 10
num_samples: 1000
num_skeletons: 10
planner: tampura_policy
print_options: ab,a,o,r
pwa: 0.2
pwk: 3.0
real_camera: false
real_execute: false
save_dir: /home/am/IsaacLab/tampura_in_isaac_lab/runs/run1729498657.9091873
symk_direction: fw
symk_selection: unordered
symk_simple: true
task: class_uncertain
vis: false
vis_graph: true
